services:
  postgres:
    image: postgres:15
    container_name: book-borrow-db
    environment:
      POSTGRES_DB: book_borrow
      POSTGRES_USER: bookborrow
      POSTGRES_PASSWORD: bookborrow123
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: